# Generated by Django 3.2.10 on 2021-12-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruangtest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='datap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('indikator', models.CharField(max_length=100)),
            ],
        ),
    ]
