# Generated by Django 3.2.10 on 2021-12-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruangtest', '0002_datap'),
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=3)),
            ],
        ),
    ]
