# Generated by Django 3.2.10 on 2021-12-21 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ruangtest', '0006_auto_20211221_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='hasil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ruangtest.result'),
        ),
    ]
