# Generated by Django 3.2.10 on 2021-12-21 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ruangtest', '0007_test_hasil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='ans1',
            field=models.CharField(blank=True, choices=[('Ya', 'ya'), ('Tidak', 'tidak')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans10',
            field=models.CharField(blank=True, choices=[('Ya', 'ya'), ('Tidak', 'tidak')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans11',
            field=models.CharField(blank=True, choices=[('Ya', 'ya'), ('Tidak', 'tidak')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans12',
            field=models.CharField(blank=True, choices=[('Ya', 'ya'), ('Tidak', 'tidak')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans13',
            field=models.CharField(blank=True, choices=[('Ya', 'ya'), ('Tidak', 'tidak')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans14',
            field=models.CharField(blank=True, choices=[('Ya', 'ya'), ('Tidak', 'tidak')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans15',
            field=models.CharField(blank=True, choices=[('Ya', 'ya'), ('Tidak', 'tidak')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans16',
            field=models.CharField(blank=True, choices=[('Ya', 'ya'), ('Tidak', 'tidak')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans17',
            field=models.CharField(blank=True, choices=[('Ya', 'ya'), ('Tidak', 'tidak')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans18',
            field=models.CharField(blank=True, choices=[('Ya', 'ya'), ('Tidak', 'tidak')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans19',
            field=models.CharField(blank=True, choices=[('Ya', 'ya'), ('Tidak', 'tidak')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans2',
            field=models.CharField(blank=True, choices=[('Ya', 'ya'), ('Tidak', 'tidak')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans20',
            field=models.CharField(blank=True, choices=[('Ya', 'ya'), ('Tidak', 'tidak')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans21',
            field=models.CharField(blank=True, choices=[('Ya', 'ya'), ('Tidak', 'tidak')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans22',
            field=models.CharField(blank=True, choices=[('Ya', 'ya'), ('Tidak', 'tidak')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans3',
            field=models.CharField(blank=True, choices=[('Ya', 'ya'), ('Tidak', 'tidak')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans4',
            field=models.CharField(blank=True, choices=[('Ya', 'ya'), ('Tidak', 'tidak')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans5',
            field=models.CharField(blank=True, choices=[('Ya', 'ya'), ('Tidak', 'tidak')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans6',
            field=models.CharField(blank=True, choices=[('Ya', 'ya'), ('Tidak', 'tidak')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans7',
            field=models.CharField(blank=True, choices=[('Ya', 'ya'), ('Tidak', 'tidak')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans8',
            field=models.CharField(blank=True, choices=[('Ya', 'ya'), ('Tidak', 'tidak')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans9',
            field=models.CharField(blank=True, choices=[('Ya', 'ya'), ('Tidak', 'tidak')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ruangtest.test'),
        ),
        migrations.AlterField(
            model_name='test',
            name='hasil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ruangtest.result'),
        ),
    ]
