# Generated by Django 3.2.10 on 2021-12-21 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruangtest', '0008_auto_20211221_1926'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test',
            new_name='dtest',
        ),
    ]
